### ISSUE TITLE
More user friendly version?

### ISSUE THREAD

**Issue by FiftyFour7250** [JustSxm/SpotifyMigrator#3]
Hey. This is exactly what I've been looking for a long time, and finally here it is. Thanks. But is it possible that more user friendly version will appear? Cause now installing Node.js, creating application… Of course, I will have to deal with this anyway, but it would be much cooler if there was ready app))

**Comment by JustSxm** [comment]
Hello, maybe. This projet was made because I couldn't find one. Though I don't really have time for now to make a new version of it.

**Comment by FiftyFour7250** [comment]
Here
https://github.com/aartek/trikatuka2
