### ISSUE TITLE
Added track log output displays the same number

### ISSUE THREAD

**Issue by NPap0** [JustSxm/SpotifyMigrator#5]
Hey, first and foremost I would like to thank you for your work as this is the first working project that migrates the liked songs playlist in order that I have found working.
Just an issue that is not so serious, I keep getting the same output let's say:
Added track #XXXXXX! where XXXXXX is always the same number. The migration is taking place normally though (adds all/different songs)

**Comment by JustSxm** [comment]
Hey there!
I'm in the process of rewriting the entire thing. I won't fix that in the current version (won't waste too much time on it) but I'll make sure it's fixed in the next version.

Thanks for your interest in the projet, might give me motivation to get back on it
