### ISSUE TITLE
App isn't working, doesn't load page after "Login" authorization 

### ISSUE THREAD

**Issue by artjxm** [JustSxm/SpotifyMigrator#8]
I've been looking for a tool to transfer all my content from one account to another in Spotify and noticed two: Trikatuka, which is great besides the thing that it mixes the favorite songs, which I find a bad think. And the other one - your SpotifyMigrator. Thank you for creating this software!!! But sad thing is this doesn't work for me. I've used VS Code to check .exe file, found out that .NET SDK 7.0+ is required (make sure to mention it in the requirements section), successfully installed it but stil couldn't manage to use this application: I can logout of my old account, then I press "Login" button, log in with fresh new profile, but then it doesn't load the page saying "This site can’t be reachedlocalhost refused to connect.". I don't really know what causes that but want to make it work. Is it possible to check what the problem is somehow? Would really apreciate any advice!!

**Comment by JustSxm** [comment]
Hi, I'll try looking into it this weekend.

The error you're mentionning sounds like a firewall or misconfiguration issue.

I'll check though, incase Spotify updated something on their end which broke the application

Please send me steps to reproduce the error.

**Comment by artjxm** [comment]
So, first thing is I login to Spotify Developer Website and create an App as shown below:
![image](https://github.com/JustSxm/SpotifyMigrator/assets/55762492/c5cd0517-ef17-44e6-8c2d-076bf2362985)
Then I added my old account user (to make it clear later I added the new account as well):
![image](https://github.com/JustSxm/SpotifyMigrator/assets/55762492/bec71f55-0849-48da-89d1-3c2beb43eef0)
Next I downloaded and unzipped the publish folder, made required implementations to the code (ClientID in wwwroot/appsettings.json and Client ID & Secret in appsettings.json).
Then I tried running an .exe file from console and didn't see anything, ran it from terminal in VS Code, found out I also need .NET SDK 7.0+, installed it and successfully started a backend, code as below:
```shell
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\tom31\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\tom31\Downloads\publish
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - -
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/blazor.webassembly.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - - - 304 - text/javascript 136.9232ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/blazor.boot.json.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - - - 304 - application/json 2.0248ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/appsettings.json - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /appsettings.json was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/appsettings.json - - - 304 - application/json 1.8146ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/dotnet.7.0.4.3fbokqc6ot.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - - - 304 - text/javascript 3.3622ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/favicon.ico - - - 404 0 - 35.4288ms
```
If I click on Logout, I get error 403, but it's an issue of my VPN (required to load Spotify page) so I use Incognito, but if I click Login, enter my credentials of the old account and boom I get an error "This site can't be reached" 
![image](https://github.com/JustSxm/SpotifyMigrator/assets/55762492/8840372f-6d86-4f57-934a-69203ede1205)

**Comment by JustSxm** [comment]
Hi, the problem comes from your app starting on port 5000, (I reopened the project myself and it seems to open on a new port aswell). To fix the problem ill add something, but I dont know if in your current environnement its gonna work.

I recommend Visual Studio to run any kind of C# Projects on Windows.

**Comment by DeanWinchesterrr** [comment]
> Hi, the problem comes from your app starting on port 5000, (I reopened the project myself and it seems to open on a new port aswell). To fix the problem ill add something, but I dont know if in your current environnement its gonna work.
> 
> I recommend Visual Studio to run any kind of C# Projects on Windows.

Did we fix the 5000 port issue, same issue here as well.

**Comment by klairvoyage** [comment]
> > Hi, the problem comes from your app starting on port 5000
>
> Did we fix the 5000 port issue, same issue here as well.

No but an easy workaround is to just change the port in the url from 5009 to 5000

**Comment by NPap0** [comment]
Same issue here as well, terminal is showing as listening on port 5000 even though the app I created has the redirect urls of 5009, maybe that mismatch is causing the issue?
